progress, workspace is not white by default.

diff --git a/devfile.yaml b/devfile.yaml
--- a/devfile.yaml
+++ b/devfile.yaml
@@ -19,3 +19,25 @@ components:
     container:
       image: quay.io/sshaaf/dls-devspaces:latest
       memoryLimit: 10Gi
+
+commands:
+  - id: setup-mta-global-settings
+    exec:
+      component: mta-dev-container
+      commandLine: |
+        TARGET_DIR="/checode/remote/data/User/globalStorage/redhat.mta-core/settings"
+        # Using the raw URL to avoid getting HTML instead of YAML
+        RAW_URL="https://raw.githubusercontent.com/sshaaf/dls-devspaces/devfile-test/provider-settings.yaml"
+        echo "Injecting MTA provider settings..."
+        mkdir -p "$TARGET_DIR"
+        # -f fails on 404, -L follows redirects, -s is silent
+        curl -fLs "$RAW_URL" -o "$TARGET_DIR/provider-settings.yaml"
+        if [ $? -eq 0 ]; then
+          echo "SUCCESS: provider-settings.yaml successfully pulled via curl."
+        else
+          echo "FAILED: to pull provider-settings.yaml. Check the URL or network."
+        fi
+
+events:
+  postStart:
+    - create-workspace-file
